### ISSUE TITLE
3rd parties collusion and user tracking

### ISSUE THREAD

**Issue by noloader** [w3c/fingerprinting-guidance#10]
Below is a screen capture of a visit to a website. The search used to find the page was _"kvm transparent bridge"_. Notice the ad on the right of the screen. The search terms are not reflected in the ads I am seeing.

I have a business trip to Chicago next month, and I made a reservation for the Westin a few days earlier. I'm getting ads based on history of unrelated sites. Similar ads show up on other unrelated sites. They have been following me for a few days now since I made the reservation.

Its kind of spooky the advertisers knew my travel itinerary and the hotel I was staying at. More concerning are the facts:
- I'm using Firefox 44.0
- Send **_Do not Track**_ is checked
- Use **_Tracking Protection**_ is checked
- **_Accept 3rd Party Cookies**_ is set to **_Never**_

I think I am following all the best practices that are available to me.

---

![westin-ad](https://cloud.githubusercontent.com/assets/3538226/12687296/e7c7a132-c69c-11e5-8e9f-f3d6b3a410fe.png)

**Comment by npdoty** [comment]
This concern (of unexpected correlation of browsing activity) is currently noted in the draft as one of the motivating privacy issues for this work: http://w3c.github.io/fingerprinting-guidance/#correlation-of-browsing-activity
In this particular case, I'm not sure if browser fingerprinting or, perhaps more likely, cookie-syncing is being used to target ads based on that prior activity on other sites.

Feel free to re-open this issue if there are additions to the fingerprinting-guidance document that would better explain the concern.
