### ISSUE TITLE
providing hooks for instrumentation/detection of fingerprinting

### ISSUE THREAD

**Issue by npdoty** [w3c/fingerprinting-guidance#11]
Per https://lists.w3.org/Archives/Public/public-privacy/2015OctDec/0096.html, it could ease fingerprinting-detection by OpenWPM, FPDetective or other tools if browsers consistently provided hooks/instrumentation for functionality that might be used for fingerprinting.

Is this guidance we could provide at spec-writing time?

/cc @englehardt

**Comment by npdoty** [comment]
We currently mention explicit hooks for enabling/disabling fingerprinting surface features:

> Explicit hooks or API flags may be used so that browser extensions or certain user agents can easily disable specific features. For example, the origin-clean flag allows control over whether an image canvas can be read, a significant fingerprinting surface. 

@englehardt, could you give examples of what hooks would be useful for instrumentation/detection?

**Comment by englehardt** [comment]
A second example of hooks for extensions to enable/disable features is [the ability to control ICE candidate exposure via a browser pref](https://hacks.mozilla.org/2015/09/controlling-webrtc-peerconnections-with-an-extension/), which was added as a direct response to privacy concerns.

I’m not sure specific measurement hooks at the API/feature level would make sense. Rather, the browser should provide a way to monitor all or a subset of calls to native APIs from an extension. Ideally, the browser would expose the object being interacted with, the property accessed (including the value returned or set), the method call (with arguments), and the originating script url.

With this raw data available a browser extension could, for example, examine calls to the `measureText()` method of `CanvasRenderingContext2D` when looking for scripts using canvas to discover a user’s fonts. Script urls are essential to determining the originator of the instrumented calls.

Our current approach is to overwrite the getters and setters of all methods and properties for any API we instrument. This approach is brittle, for example we’ve observed benign scripts overwrite our instrumentation. It’s also detectable by scripts, though we haven’t observed any scripts doing this yet. A built in monitor would be more reliable, undetectable, and would likely have less of a performance impact.

/cc @gunesacar who may have additional input.

**Comment by gunesacar** [comment]
> Rather, the browser should provide a way to monitor all or a subset of calls to native APIs from an extension.

I think that's a pretty good summary of what is needed for instrumentation & detection.

If you like, here are some concrete cases where limited browser support made fingerprinting detection harder:
- [Issue 545509 - chromium - Getters not working on Plugin objects](https://crbug.com/545509)
- [Issue 470671 - chromium - Unable to override host/native objects (for example, CSSStyleDeclaration)](https://crbug.com/470671)
- [Issue 478183 - chromium - Programmatic injection of run_at = document_start content scripts](https://crbug.com/478183)

For instance, due to [crbug.com/478183](https://crbug.com/478183), it is not possible to guarantee that extension/instrumentation code will run before the page scripts, leading to potential false negatives in detection (e.g. https://github.com/ghostwords/chameleon/issues/5).

Chrome bug [#470671](https://crbug.com/470671) was the main reason why we had to modify the browser native code in FPDetective, which is not an option for tracking protection extensions.

I'm sure @ghostwords, who filed all the above bugs, can contribute to this discussion.

**Comment by ghostwords** [comment]
Totally, ideally we'd have a dedicated JavaScript instrumentation API, a performant, non-fragile and non-page breaking way of observing (and potentially modifying) all JavaScript activity from an extension, but for now fixes to gaps in our existing monitoring hacks would be great. Here is another problem: figuring out originating scripts [mostly works, but has a number of issues](https://github.com/ghostwords/chameleon/blob/a1a6c20616a56b4896240536aafef76cd6cde0ca/src/js/injected.js#L164-L217).

Beyond JavaScript, we also want extension-accessible ways of inspecting and potentially modifying the rest of the browser's activity as [fingerprinting techniques are not limited to JavaScript](http://www.chromium.org/Home/chromium-security/client-identification-mechanisms). Some Chrome examples:
- [WebRequest API: allow extensions to read response body](https://bugs.chromium.org/p/chromium/issues/detail?id=487422)
- [WebRequest API: allow extension to edit response body](https://bugs.chromium.org/p/chromium/issues/detail?id=104058)
- [Add/extend API to enable Local Storage management for extensions](https://bugs.chromium.org/p/chromium/issues/detail?id=78093)

**Comment by englehardt** [comment]
As an additional example, it's not possible to monitor `window.location` in Firefox using the getter/setter approach as it's disallowed for security reasons. See [Bug 143369](https://bugzilla.mozilla.org/show_bug.cgi?id=143369#c5) and [Bug 36946](https://bugzilla.mozilla.org/show_bug.cgi?id=36946).

**Comment by npdoty** [comment]
I've added a little more text regarding the points for implementers on providing or enabling instrumentation, but for the most part I'm getting the sense that further instrumentability is mostly up to implementations and not something to be considered in drafting the specification for a feature.

>  Implementers can facilitate detectability by providing or enabling instrumentation so that users or third parties are able to calculate when fingerprinting surface is being accessed. Of particular importance for instrumentation are: access to all the different sources of fingerprinting surface; identification of the originating script; avoiding exposure that instrumentation is taking place. Beyond the minimization practice described above, these are largely implementation-specific (rather than Web specification) features.

Context: https://w3c.github.io/fingerprinting-guidance/#detectability

If there's more that could be done in this document, please let us know. Otherwise, I'd suggest that we try to compile a list of these browser bugs somewhere and close this issue.

**Comment by englehardt** [comment]
This sounds reasonable to me, thanks Nick!
