### ISSUE TITLE
Provide advice on whether this spec. exposes similar information 

### ISSUE THREAD

**Issue by dwsinger** [w3c/fingerprinting-guidance#15]
something like:

do not write in your spec. that this doesn’t make fingerprinting worse because similar information is available in other ways. (a) similar is not the same as identical. (b) the other ways almost certainly have differences in difficulty of use and ubiquity of availability (c) such disclaimers have a risk of being circular (two or more specs that end up referencing each other to support the claim that they make the situation no worse).

**Comment by npdoty** [comment]
See last paragraph of this section: https://w3c.github.io/fingerprinting-guidance/#identifying
