### ISSUE TITLE
add code example for fingerprint icon

### ISSUE THREAD

**Issue by samuelweiler** [w3c/fingerprinting-guidance#18]
6.1 suggests adding the fingerprint icon.  add a code snippet showing how to do that in w3c specs?  also, christine says this is less pretty than she remembers in a previous version - is there a better icon to use?

**Comment by npdoty** [comment]
I'm asking around about the original version of the icon. It might look fuzzier just because it isn't optimized with a "retina" version for the high-density screens we're all using these days.

**Comment by npdoty** [comment]
Added code snippet in e4b5d1b9076a8303f9d8c2b5fb34cb99545079b9.

**Comment by npdoty** [comment]
I think we might be able to use an SVG, which would resolve the image resolution issue, and we might also be able to share an icon with lots of other documents (in WHATWG and HTML) that want to indicate this in common.

**Comment by npdoty** [comment]
We have a code snippet in the Note, so I suggest we can close this issue for now and come back to it once there's some agreement on:
* an SVG icon everyone can use
* CSS for all TRs or functionality in Bikeshed/Respec to automatically add the image to appropriate paragraphs

**Comment by npdoty** [comment]
Closing for now, waiting on image and better tooling resolution in linked issues.
