### ISSUE TITLE
Example for Best Practice 2?

### ISSUE THREAD

**Issue by jasonanovak** [w3c/fingerprinting-guidance#22]
For Best Practice 2, I think that it would be helpful to add an example of how to decrease fingerprinting surface while maintaining functionally-comparable designs.  One example elsewhere (e.g. in web-audio-api) was to add jitter (dithering) and quantization to prevent fingerprinting on outputLatency.  Another example would be to provide rounded values instead of exact values (or better yet ENUMs representing the semantic meaning of the rounded values where possible).

**Comment by npdoty** [comment]
http://w3c.github.io/fingerprinting-guidance/#api-minimization
The "only the entropy necessary" best practice includes some examples of quantization and enumeration (with battery status and proximity as the example APIs).

Any specific examples on jitter/fuzzing or other good examples of enumeration would be most welcome, either links or a PRs.

**Comment by jasonanovak** [comment]
Makes sense.  Will create separate issues / PRs for additional examples as they arise.
