### ISSUE TITLE
Additional Example for Best Practice 5

### ISSUE THREAD

**Issue by jasonanovak** [w3c/fingerprinting-guidance#24]
As of macOS Mojave and iOS 12, Safari mitigates font fingerprinting by returning only the system fonts that are present on all macOS or iOS installations.  While the draft note currently considers returning a limited or set number of fonts, the idea of returning a constant set of fonts a la macOS Mojave and iOS 12 could be added to Best Practice 5.

**Comment by npdoty** [comment]
this is more an implementation-specific mitigation rather than something we can spec out, but I've added a paragraph to note it, and the font whitelist is a good example as it's in Tor Browser, Firefox and Safari, I believe.

**Comment by jasonanovak** [comment]
> Some implementations may also limit the entropy of fingerprinting surface by not exposing different capabilities for different devices or installations of a user agent. Font lists, for example, can be limited to a whitelist commonly available on all devices that run a particular browser or operating system (as implemented in Tor Browser, Firefox and Safari).

Looks good to me.
