### ISSUE TITLE
Reference INRIA’s Hiding in the Crowd: an Analysis of the Effectiveness of Browser Fingerprinting at Large Scale?

### ISSUE THREAD

**Issue by jasonanovak** [w3c/fingerprinting-guidance#25]
May be worth adding a reference to [INRIA’s Hiding in the Crowd: an Analysis of the Effectiveness of Browser Fingerprinting at Large Scale](https://www.doc.ic.ac.uk/~maffeis/331/EffectivenessOfFingerprinting.pdf) to the Research section.

**Comment by npdoty** [comment]
On the list as #16
