### ISSUE TITLE
Discuss impact of revealing hardware information to the web vis-a-vis entropy disclosed.

### ISSUE THREAD

**Issue by jasonanovak** [w3c/fingerprinting-guidance#26]
As specs increasingly are revealing hardware information to the web, the entropy that is being released to the web may vary in how identifiable it is.  As a result, it may be worth adding some language re: having specification authors consider whether their specific adds entropy that is:
- User specific;
- Device class / type specific;
- Device specific

**Comment by npdoty** [comment]
I think the key difference between revealing hardware, hardware class and user configuration is the distribution of values -- characteristics that could potentially have many different values but actually just have a few values connected to large groups like hardware class may be less severe than often-customized user configuration details.

Let me know what you think of the text change.

**Comment by jasonanovak** [comment]
@npdoty to confirm the text change is:

> Different data sources may provide different distributions of variation; for example, some characteristics may reveal a common hardware class while other characteristics may reveal user configurations that vary between individual people.

under the definition of entropy in Section 5?

Assuming that's the case, I think that overall the direction and edit make sense.
