### ISSUE TITLE
Document duplication of fingerprinting surface if it appears at multiple places

### ISSUE THREAD

**Issue by jumde** [w3c/fingerprinting-guidance#28]
From the TPAC discussion: https://www.w3.org/2018/10/26-privacy-minutes.html

If the fingerprinting surface appears at multiple places, document duplication. So that when trying to mitigate fingerprinting, its mitigated in both places.

**Comment by npdoty** [comment]
I think this is the same issue as #15, which has a pending resolution; but if it's a different point, feel free to re-open.
