### ISSUE TITLE
Best practices black background

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/fingerprinting-guidance#36]
The practice summary currently renders as:

![Screenshot 2019-05-06 16 04 42](https://user-images.githubusercontent.com/870154/57208760-cea5a900-7018-11e9-9d0c-684aa07e8823.png)

https://www.w3.org/TR/fingerprinting-guidance/#bp-summary

**Comment by marcoscaceres** [comment]
This seems to be a ReSpec issue. Will fix.

**Comment by marcoscaceres** [comment]
Fixed in latest ReSpec release.

**Comment by marcoscaceres** [comment]
Reopening, as the issue is still on the TR space:
https://www.w3.org/TR/fingerprinting-guidance/#bp-summary

@npdoty, not sure who the team contact is... maybe you could ping them?... the spec can be either regenerated, or the CSS can be fixed directly in the published document.

**Comment by wseltzer** [comment]
Thanks @marcoscaceres, now fixed in the published doc.

**Comment by marcoscaceres** [comment]
Just a heads up that I’m also fixing the Best Practice boxes so they get displayed correctly. However, the fingerprinting img will need to be repositioned. 

I might take the fingerprint image and bake it into ReSpec too, as it’s generally useful.
