### ISSUE TITLE
Should we recommend Client Hints as method for converting passive surfaces to active?

### ISSUE THREAD

**Issue by JensenPaul** [w3c/fingerprinting-guidance#42]
In the [Best Practice 1](https://w3c.github.io/fingerprinting-guidance/#avoid-passive-increases) section should we recommend [Client Hints](https://httpwg.org/http-extensions/client-hints.html) as the way to convert HTTP-level passive fingerprintable surfaces to active ones?

**Comment by npdoty** [comment]
Client Hints are noted in Best Practice 6 "Require servers to advertise or opt in to access data", in the section on Detectability. Does that make sense or does it need to be included in "weighing increased fingerprinting surface"?

**Comment by npdoty** [comment]
Closing now (as included in Best Practice 6), but can re-open if it's not clear.
