### ISSUE TITLE
title of the document should clarify mitigation

### ISSUE THREAD

**Issue by npdoty** [w3c/fingerprinting-guidance#5]
via Hadley

**Comment by npdoty** [comment]
Hadley agrees that "mitigation" would be a useful word to include. @mnot, if you have specific suggestions, this would be the right issue to add them.

**Comment by npdoty** [comment]
In a108b71e889854216873b835430d6551d412b821, trying: "Mitigating Fingerprinting in Web Specifications". @torgo, @mnot, what do you think?

**Comment by mnot** [comment]
Perhaps "Mitigating _Browser_ Fingerprinting..." 

or "client".

**Comment by hadleybeeman** [comment]
Thanks, @npdoty — we are happy with the name change.
