### ISSUE TITLE
additional existing fingerprinting vectors to mention

### ISSUE THREAD

**Issue by noloader** [w3c/fingerprinting-guidance#7]
The following subject matter could be discussed.

(1) tracking begins at the first network/transport message. In the case of TCP/IP, that's the `TCP/SYN` message. it seems like a good candidate for inclusion because some user agents, like the Tor browser, address the issue while many other users agents do not.

(2) `ETAGS` can be used for tracking. This is a well known vector.

(3) Public Keys used in [Public Key Pinning with Overrides](https://tools.ietf.org/html/rfc7469) probably cannot be used for tracking. The authors attempted to ensure a known-good pinset that was broken by the attacker could not be used for tracking purposes. They did so by calling out the reporting as a `SHOULD NOT`.

(4) CSP and SRI seems like they could be used for tracking because of the reporting mechanisms.

Browsers don't operate in a vacuum; they are bundled with a desktop or device. Some other notables that leaks information, especially with a mobile device:

(5) various radios

The leak with (5) can be made even more interesting because things the channel and the carrier are not usually authenticated. That is, I can set up a Wifi hotspot, I can call it **_`attwifi`**_, and various devices will camp to it automatically. The same can be done with 2G/3G/4G using [GNU Radio](https://gnuradio.org/redmine/projects/gnuradio) because only the handset is authenticated to the network (and not vice-versa). Then, all browser traffic over the physical channel will leak information.

**Comment by npdoty** [comment]
While I'm not sure this document can or should become a list of all known tracking or fingerprinting vectors, these could be useful for providing examples (see #6).

Also in this category:
- tools for passive fingerprinting (p0f) / fingerprinting at lower layers
- device sensors, which often operate across origin
